"""description of changes

Revision ID: 1a5b9e752a27
Revises: 7a1ffc65cb81
Create Date: 2024-11-07 03:15:14.535766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5b9e752a27'
down_revision: Union[str, None] = '7a1ffc65cb81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'embedding')
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.add_column('products', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
